# Generated by Django 3.2.24 on 2024-02-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent object edit.', verbose_name='edited at'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, help_text='List of ingredients (max 500 chars).', max_length=500, null=True, verbose_name='ingredients'),
        ),
    ]
